##Name: Laiqa Ali
##CMS id: 406448
##Section: BSCS-12A

#Lab01: Introduction to ML

####1. Python Code Cell

In [1]:
print("Hello, Machine Learning World!")

Hello, Machine Learning World!


In [ ]:
a = 5
b = 3
print(a + b)

8


####2. Using Google Drive With **Colab**

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [9]:
import pandas as pd
# importing the sample csv file from drive
data = pd.read_csv('/content/drive/MyDrive/Sample-Spreadsheet-10-rows.csv' , encoding='latin1')
print(data)

    1   Eldon Base for stackable storage shelf, platinum Muhammed MacIntyre  \
0   2  1.7 Cubic Foot Compact "Cube" Office Refrigera...       Barry French   
1   3   Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl       Barry French   
2   4                                               R380      Clay Rozendal   
3   5                           Holmes HEPA Air Purifier     Carlos Soltero   
4   6  G.E. Longer-Life Indoor Recessed Floodlight Bulbs     Carlos Soltero   
5   7  Angle-D Binders with Locking Rings, Label Holders       Carl Jackson   
6   8            SAFCO Mobile Desk Side File, Wire Frame       Carl Jackson   
7   9              SAFCO Commercial Wire Shelving, Black     Monica Federle   
8  10                                          Xerox 198    Dorothy Badders   

     3  -213.25   38.94     35  Nunavut          Storage & Organization   0.8  
0  293   457.81  208.16  68.02  Nunavut                      Appliances  0.58  
1  293    46.71    8.69   2.99  Nunavut  Binders 

In [12]:
# making the output csv file
data.to_csv('/content/drive/MyDrive/output_data.csv')

In [23]:
# unmounting the google drive
from google.colab import drive
drive.flush_and_unmount()

####3. Numpy Introduction

*   Example

In [24]:
import numpy as np

heights = np.array([1.75, 1.80, 1.65]) # in meters
weights = np.array([65, 78, 50]) # in kg

bmi = weights / (heights ** 2)
print(bmi)

[21.2244898  24.07407407 18.36547291]


####4. Connection to ML concepts

*   Data Preprocessing

In [26]:
import numpy as np
data = np.array([4.0, 5.0, 6.0, 8.0, 10.0])
normalized_data = (data - np.mean(data)) / np.std(data)
print(normalized_data)

[-1.2070197  -0.74278135 -0.27854301  0.64993368  1.57841037]


*   Matrix Operations

In [27]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


*   Linear Regression

In [28]:
import numpy as np
X = np.array([[1, 2], [3, 4], [5, 6]])
beta = np.array([0.5, 1.5])
b = 0.1
y_pred = np.dot(X, beta) + b
print(y_pred)

[ 3.6  7.6 11.6]


####5. Key Numpy Concepts

*   Array vs Lists

In [29]:
# Python Lists
list_a = [1, 2, 3]
list_b = [4, 5, 6]
result = [a + b for a, b in zip(list_a, list_b)]
print(result) # Output: [5, 7, 9]

[5, 7, 9]


In [30]:
# Numpy Arrays
import numpy as np
a= np.array([1,2,3], )
b = np.array([4,5,6])
print(a+b)

[5 7 9]


*   Creating Numpy Arrays

In [31]:
# From lists
import numpy as np
print(np.array([1,2,3,4]))

# Using the np.zeros and np.ones
zero = np.zeros((3,3))
one = np.ones((2,4))
random = np.random.random((2,3))
print("zeros array: \n", zero)
print("ones array: \n", one)
print("random array: \n", random )

[1 2 3 4]
zeros array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
random array: 
 [[0.82660968 0.25387738 0.64643908]
 [0.49519349 0.96314769 0.08960867]]


*   Basic Array Operations

In [36]:
# addition, subtraction and multiplication
a= np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:\n", a + b) # Output: [5, 7, 9]
print("Subtraction: \n", a * b) # Output: [4, 10, 18]

# broadcasting
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])
print("Broadcasting:")
print(a+b)

Addition:
 [5 7 9]
Subtraction: 
 [ 4 10 18]
Broadcasting:
[[2 4 6]
 [5 7 9]]


*   Reshaping and flattening Arrays

In [37]:
# reshaping
a = np.array([1, 2, 3, 4, 5, 6])
a_reshaped = a.reshape(2, 3) # 2 rows, 3 columns
print("reshaped: \n", a_reshaped)

# flattening
a_flat = a_reshaped.flatten()
print("Flattened: \n", a_flat) # Output: [1, 2, 3, 4, 5, 6]

reshaped: 
 [[1 2 3]
 [4 5 6]]
Flattened: 
 [1 2 3 4 5 6]


####6. Hands On Coding

In [39]:
# Creating and Manipulating Arrays
# Creating a 1D Array from a List
import numpy as np
array_1d = np.array([10, 20, 30, 40])
print("1D Array\n",array_1d)

# Creating a 2D Array (Matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array\n",array_2d)

# Performing Operations
array_sum = array_1d + 5 # Add 5 to every element
print("Adding 5 to every element of 1D array:")
print(array_sum)

1D Array
 [10 20 30 40]
2D Array
 [[1 2 3]
 [4 5 6]]
Adding 5 to every element of 1D array:
[15 25 35 45]


In [41]:
# Generating a random matrix and performing operations
# Generating a Random Matrix
random_matrix = np.random.random((3, 3))
print("Random Matrix:")
print(random_matrix)
# Matrix Operations
random_matrix_scaled = random_matrix * 100 # Scale all values by 100
print("Scaled Matrix:")
print(random_matrix_scaled)

Random Matrix:
[[0.65099589 0.90052503 0.19893506]
 [0.27557272 0.69078378 0.89951249]
 [0.86905655 0.25399067 0.20172474]]
Scaled Matrix:
[[65.09958885 90.05250327 19.89350643]
 [27.55727234 69.07837839 89.95124945]
 [86.90565466 25.39906732 20.17247378]]


In [42]:
# Reshaping and Slicing
# Reshaping Arrays
reshaped_array = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3) # 2 rows, 3 columns
print("reshaped Array: ")
print(reshaped_array)
# Slicing Arrays
# Slice first two rows and first two columns
sliced_array = reshaped_array[:2, :2]
print("Sliced Array: ")
print(sliced_array)

reshaped Array: 
[[1 2 3]
 [4 5 6]]
Sliced Array: 
[[1 2]
 [4 5]]


###MINI CHALLENGE

In [ ]:
def normalization_func(a):
  #normalize the array between 0 and 1
  normalized_a = (a-np.min(a))/(np.max(a)-np.min(a))

  #printing the normalized array
  print("Normalized Matrix: \n")
  print(normalized_a)

#randomly generated Array of any size
random_matrix = np.random.random((3,3))
print("Random Matrix: \n")
print(random_matrix)
normalization_func(random_matrix)

Random: 
[[0.06809549 0.15330932 0.16637381]
 [0.38082167 0.31628016 0.22882965]
 [0.98235774 0.66277054 0.99290891]]
Normalized 
[[0.         0.09214165 0.10626826]
 [0.33815056 0.26836188 0.17380171]
 [0.98859102 0.64302165 1.        ]]


###Question:
After this, can you explain how this normalization technique will be critical in upcoming weeks when we deal with dataset preprocessing for ML models?
###Answer:
Normalization is crucial for ML model preprocessing. It ensures features have a similar scale, preventing dominant features from skewing results. This improves model convergence, feature contributions, performance, and compatibility with certain algorithms.